#!/bin/bash

# Detect if it's a 1st time installation

# Recommended by debian policy manual
set -e

# Print a greeting message on a 1st time installation

# Here the script is called with the configure argument
# but not provided with a version like so:
# postinst configure
# For upgrades, reconfigures, and everything else its:
# postinst configure 1.2-1

if [ "${1}" == "configure" ] && [ -z "${2}" ]
then
  echo ""
  echo "################################"
  echo "# Hook Scripts for SnapRAID-DAILY"
  echo "################################"
  echo ""
  echo "  To get started have a look at the manual entry:"
  echo "  snapraid-daily-apprise-hook(1)"
  echo "  snapraid-daily-healthchecks-hook(1)"
  echo "  snapraid-daily-service-hook(1)"
  echo ""
  echo "  $ man snapraid-daily-apprise-hook"
  echo "  $ man snapraid-daily-healthchecks-hook"
  echo "  $ man snapraid-daily-service-hook"
  echo ""
  exit 0
else
  exit 0
fi


